2021-01-27 19:49:52,762 - Not authorized.
Traceback (most recent call last):
  File "C:\Users\rodri\PythonProjects\PhiloBot-Test-ENV\TWITTER_TEST_ENV\Posting\posting.py", line 75, in posting
    tweets_conta = self.obter_tweets(self.api, random_conta)
  File "C:\Users\rodri\PythonProjects\PhiloBot-Test-ENV\TWITTER_TEST_ENV\Posting\posting.py", line 40, in obter_tweets
    resultados = api.user_timeline(screen_name=USERNAME_ACCOUNT,
  File "C:\Users\rodri\AppData\Local\Programs\Python\Python39\lib\site-packages\tweepy\binder.py", line 253, in _call
    return method.execute()
  File "C:\Users\rodri\AppData\Local\Programs\Python\Python39\lib\site-packages\tweepy\binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: Not authorized.
2021-01-27 19:49:53,101 - 'PostingClass' object has no attribute 'tweets'
Traceback (most recent call last):
  File "C:\Users\rodri\PythonProjects\PhiloBot-Test-ENV\TWITTER_TEST_ENV\Posting\posting.py", line 86, in posting
    items = ("\n".join(self.tweets))
AttributeError: 'PostingClass' object has no attribute 'tweets'
2021-01-27 20:00:28,829 - Not authorized.
Traceback (most recent call last):
  File "C:\Users\rodri\PythonProjects\PhiloBot-Test-ENV\TWITTER_TEST_ENV\Posting\posting.py", line 74, in posting
    tweets_conta = self.obter_tweets(self.api, random_conta)
  File "C:\Users\rodri\PythonProjects\PhiloBot-Test-ENV\TWITTER_TEST_ENV\Posting\posting.py", line 39, in obter_tweets
    resultados = api.user_timeline(screen_name=USERNAME_ACCOUNT,
  File "C:\Users\rodri\AppData\Local\Programs\Python\Python39\lib\site-packages\tweepy\binder.py", line 253, in _call
    return method.execute()
  File "C:\Users\rodri\AppData\Local\Programs\Python\Python39\lib\site-packages\tweepy\binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: Not authorized.
2021-01-27 20:00:29,235 - 'PostingClass' object has no attribute 'tweets'
Traceback (most recent call last):
  File "C:\Users\rodri\PythonProjects\PhiloBot-Test-ENV\TWITTER_TEST_ENV\Posting\posting.py", line 85, in posting
    items = ("\n".join(self.tweets))
AttributeError: 'PostingClass' object has no attribute 'tweets'
2021-01-27 20:28:03,650 - Not authorized.
Traceback (most recent call last):
  File "C:\Users\rodri\PythonProjects\PhiloBot-Test-ENV\TWITTER_TEST_ENV\Posting\posting.py", line 77, in posting
    tweets_conta = self.obter_tweets(self.api, random_conta)
  File "C:\Users\rodri\PythonProjects\PhiloBot-Test-ENV\TWITTER_TEST_ENV\Posting\posting.py", line 39, in obter_tweets
    resultados = api.user_timeline(screen_name=USERNAME_ACCOUNT,
  File "C:\Users\rodri\AppData\Local\Programs\Python\Python39\lib\site-packages\tweepy\binder.py", line 253, in _call
    return method.execute()
  File "C:\Users\rodri\AppData\Local\Programs\Python\Python39\lib\site-packages\tweepy\binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: Not authorized.
2021-01-27 20:28:03,998 - 'PostingClass' object has no attribute 'tweets'
Traceback (most recent call last):
  File "C:\Users\rodri\PythonProjects\PhiloBot-Test-ENV\TWITTER_TEST_ENV\Posting\posting.py", line 88, in posting
    items = ("\n".join(self.tweets))
AttributeError: 'PostingClass' object has no attribute 'tweets'
2021-01-27 20:34:28,194 - Not authorized.
Traceback (most recent call last):
  File "C:\Users\rodri\PythonProjects\PhiloBot-Test-ENV\TWITTER_TEST_ENV\Posting\posting.py", line 77, in posting
    tweets_conta = self.obter_tweets(self.api, random_conta)
  File "C:\Users\rodri\PythonProjects\PhiloBot-Test-ENV\TWITTER_TEST_ENV\Posting\posting.py", line 39, in obter_tweets
    resultados = api.user_timeline(screen_name=USERNAME_ACCOUNT,
  File "C:\Users\rodri\AppData\Local\Programs\Python\Python39\lib\site-packages\tweepy\binder.py", line 253, in _call
    return method.execute()
  File "C:\Users\rodri\AppData\Local\Programs\Python\Python39\lib\site-packages\tweepy\binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: Not authorized.
2021-01-27 20:35:30,809 - Not authorized.
Traceback (most recent call last):
  File "C:\Users\rodri\PythonProjects\PhiloBot-Test-ENV\TWITTER_TEST_ENV\Posting\posting.py", line 77, in posting
    tweets_conta = self.obter_tweets(self.api, random_conta)
  File "C:\Users\rodri\PythonProjects\PhiloBot-Test-ENV\TWITTER_TEST_ENV\Posting\posting.py", line 39, in obter_tweets
    resultados = api.user_timeline(screen_name=USERNAME_ACCOUNT,
  File "C:\Users\rodri\AppData\Local\Programs\Python\Python39\lib\site-packages\tweepy\binder.py", line 253, in _call
    return method.execute()
  File "C:\Users\rodri\AppData\Local\Programs\Python\Python39\lib\site-packages\tweepy\binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: Not authorized.
2021-01-27 20:35:37,810 - Not authorized.
Traceback (most recent call last):
  File "C:\Users\rodri\PythonProjects\PhiloBot-Test-ENV\TWITTER_TEST_ENV\Posting\posting.py", line 77, in posting
    tweets_conta = self.obter_tweets(self.api, random_conta)
  File "C:\Users\rodri\PythonProjects\PhiloBot-Test-ENV\TWITTER_TEST_ENV\Posting\posting.py", line 39, in obter_tweets
    resultados = api.user_timeline(screen_name=USERNAME_ACCOUNT,
  File "C:\Users\rodri\AppData\Local\Programs\Python\Python39\lib\site-packages\tweepy\binder.py", line 253, in _call
    return method.execute()
  File "C:\Users\rodri\AppData\Local\Programs\Python\Python39\lib\site-packages\tweepy\binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: Not authorized.
2021-01-27 20:37:40,498 - Not authorized.
Traceback (most recent call last):
  File "C:\Users\rodri\PythonProjects\PhiloBot-Test-ENV\TWITTER_TEST_ENV\Posting\posting.py", line 77, in posting
    tweets_conta = self.obter_tweets(self.api, random_conta)
  File "C:\Users\rodri\PythonProjects\PhiloBot-Test-ENV\TWITTER_TEST_ENV\Posting\posting.py", line 39, in obter_tweets
    resultados = api.user_timeline(screen_name=USERNAME_ACCOUNT,
  File "C:\Users\rodri\AppData\Local\Programs\Python\Python39\lib\site-packages\tweepy\binder.py", line 253, in _call
    return method.execute()
  File "C:\Users\rodri\AppData\Local\Programs\Python\Python39\lib\site-packages\tweepy\binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: Not authorized.
2021-01-27 20:46:30,206 - ERRO - NAO AUTORIZADO
Traceback (most recent call last):
  File "C:\Users\rodri\PythonProjects\PhiloBot-Test-ENV\TWITTER_TEST_ENV\Posting\posting.py", line 79, in posting
    self.tweets_conta = self.obter_tweets(self.api, random_conta)
  File "C:\Users\rodri\PythonProjects\PhiloBot-Test-ENV\TWITTER_TEST_ENV\Posting\posting.py", line 39, in obter_tweets
    resultados = api.user_timeline(screen_name=USERNAME_ACCOUNT,
  File "C:\Users\rodri\AppData\Local\Programs\Python\Python39\lib\site-packages\tweepy\binder.py", line 253, in _call
    return method.execute()
  File "C:\Users\rodri\AppData\Local\Programs\Python\Python39\lib\site-packages\tweepy\binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: Not authorized.
2021-01-27 20:46:30,206 - Not authorized.
Traceback (most recent call last):
  File "C:\Users\rodri\PythonProjects\PhiloBot-Test-ENV\TWITTER_TEST_ENV\Posting\posting.py", line 79, in posting
    self.tweets_conta = self.obter_tweets(self.api, random_conta)
  File "C:\Users\rodri\PythonProjects\PhiloBot-Test-ENV\TWITTER_TEST_ENV\Posting\posting.py", line 39, in obter_tweets
    resultados = api.user_timeline(screen_name=USERNAME_ACCOUNT,
  File "C:\Users\rodri\AppData\Local\Programs\Python\Python39\lib\site-packages\tweepy\binder.py", line 253, in _call
    return method.execute()
  File "C:\Users\rodri\AppData\Local\Programs\Python\Python39\lib\site-packages\tweepy\binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: Not authorized.
2021-01-27 20:51:12,106 - ERRO - NAO AUTORIZADO
Traceback (most recent call last):
  File "C:\Users\rodri\PythonProjects\PhiloBot-Test-ENV\TWITTER_TEST_ENV\Posting\posting.py", line 84, in posting
    self.tweets_conta = self.obter_tweets(self.api, random_conta)
  File "C:\Users\rodri\PythonProjects\PhiloBot-Test-ENV\TWITTER_TEST_ENV\Posting\posting.py", line 41, in obter_tweets
    resultados = api.user_timeline(screen_name=USERNAME_ACCOUNT,
  File "C:\Users\rodri\AppData\Local\Programs\Python\Python39\lib\site-packages\tweepy\binder.py", line 253, in _call
    return method.execute()
  File "C:\Users\rodri\AppData\Local\Programs\Python\Python39\lib\site-packages\tweepy\binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: Not authorized.
2021-01-27 20:51:12,106 - Not authorized.
Traceback (most recent call last):
  File "C:\Users\rodri\PythonProjects\PhiloBot-Test-ENV\TWITTER_TEST_ENV\Posting\posting.py", line 84, in posting
    self.tweets_conta = self.obter_tweets(self.api, random_conta)
  File "C:\Users\rodri\PythonProjects\PhiloBot-Test-ENV\TWITTER_TEST_ENV\Posting\posting.py", line 41, in obter_tweets
    resultados = api.user_timeline(screen_name=USERNAME_ACCOUNT,
  File "C:\Users\rodri\AppData\Local\Programs\Python\Python39\lib\site-packages\tweepy\binder.py", line 253, in _call
    return method.execute()
  File "C:\Users\rodri\AppData\Local\Programs\Python\Python39\lib\site-packages\tweepy\binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: Not authorized.
2021-01-27 20:52:48,442 - ERRO - NAO AUTORIZADO
Traceback (most recent call last):
  File "C:\Users\rodri\PythonProjects\PhiloBot-Test-ENV\TWITTER_TEST_ENV\Posting\posting.py", line 84, in posting
    self.tweets_conta = self.obter_tweets(self.api, random_conta)
  File "C:\Users\rodri\PythonProjects\PhiloBot-Test-ENV\TWITTER_TEST_ENV\Posting\posting.py", line 41, in obter_tweets
    resultados = api.user_timeline(screen_name=USERNAME_ACCOUNT,
  File "C:\Users\rodri\AppData\Local\Programs\Python\Python39\lib\site-packages\tweepy\binder.py", line 253, in _call
    return method.execute()
  File "C:\Users\rodri\AppData\Local\Programs\Python\Python39\lib\site-packages\tweepy\binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: Not authorized.
2021-01-27 20:52:48,442 - Not authorized.
Traceback (most recent call last):
  File "C:\Users\rodri\PythonProjects\PhiloBot-Test-ENV\TWITTER_TEST_ENV\Posting\posting.py", line 84, in posting
    self.tweets_conta = self.obter_tweets(self.api, random_conta)
  File "C:\Users\rodri\PythonProjects\PhiloBot-Test-ENV\TWITTER_TEST_ENV\Posting\posting.py", line 41, in obter_tweets
    resultados = api.user_timeline(screen_name=USERNAME_ACCOUNT,
  File "C:\Users\rodri\AppData\Local\Programs\Python\Python39\lib\site-packages\tweepy\binder.py", line 253, in _call
    return method.execute()
  File "C:\Users\rodri\AppData\Local\Programs\Python\Python39\lib\site-packages\tweepy\binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: Not authorized.
2021-01-27 20:57:24,039 - ERRO - NAO AUTORIZADO
Traceback (most recent call last):
  File "C:\Users\rodri\PythonProjects\PhiloBot-Test-ENV\TWITTER_TEST_ENV\Posting\posting.py", line 79, in posting
    self.tweets_conta = self.obter_tweets(self.api, random_conta)
  File "C:\Users\rodri\PythonProjects\PhiloBot-Test-ENV\TWITTER_TEST_ENV\Posting\posting.py", line 39, in obter_tweets
    resultados = api.user_timeline(screen_name=USERNAME_ACCOUNT,
  File "C:\Users\rodri\AppData\Local\Programs\Python\Python39\lib\site-packages\tweepy\binder.py", line 253, in _call
    return method.execute()
  File "C:\Users\rodri\AppData\Local\Programs\Python\Python39\lib\site-packages\tweepy\binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: Not authorized.
2021-01-27 20:57:24,039 - Not authorized.
Traceback (most recent call last):
  File "C:\Users\rodri\PythonProjects\PhiloBot-Test-ENV\TWITTER_TEST_ENV\Posting\posting.py", line 79, in posting
    self.tweets_conta = self.obter_tweets(self.api, random_conta)
  File "C:\Users\rodri\PythonProjects\PhiloBot-Test-ENV\TWITTER_TEST_ENV\Posting\posting.py", line 39, in obter_tweets
    resultados = api.user_timeline(screen_name=USERNAME_ACCOUNT,
  File "C:\Users\rodri\AppData\Local\Programs\Python\Python39\lib\site-packages\tweepy\binder.py", line 253, in _call
    return method.execute()
  File "C:\Users\rodri\AppData\Local\Programs\Python\Python39\lib\site-packages\tweepy\binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: Not authorized.
2021-01-27 21:00:26,425 - ERRO - NAO AUTORIZADO
Traceback (most recent call last):
  File "C:\Users\rodri\PythonProjects\PhiloBot-Test-ENV\TWITTER_TEST_ENV\Posting\posting.py", line 79, in posting
    self.tweets_conta = self.obter_tweets(self.api, random_conta)
  File "C:\Users\rodri\PythonProjects\PhiloBot-Test-ENV\TWITTER_TEST_ENV\Posting\posting.py", line 39, in obter_tweets
    resultados = api.user_timeline(screen_name=USERNAME_ACCOUNT,
  File "C:\Users\rodri\AppData\Local\Programs\Python\Python39\lib\site-packages\tweepy\binder.py", line 253, in _call
    return method.execute()
  File "C:\Users\rodri\AppData\Local\Programs\Python\Python39\lib\site-packages\tweepy\binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: Not authorized.
2021-01-27 21:00:26,426 - Not authorized.
Traceback (most recent call last):
  File "C:\Users\rodri\PythonProjects\PhiloBot-Test-ENV\TWITTER_TEST_ENV\Posting\posting.py", line 79, in posting
    self.tweets_conta = self.obter_tweets(self.api, random_conta)
  File "C:\Users\rodri\PythonProjects\PhiloBot-Test-ENV\TWITTER_TEST_ENV\Posting\posting.py", line 39, in obter_tweets
    resultados = api.user_timeline(screen_name=USERNAME_ACCOUNT,
  File "C:\Users\rodri\AppData\Local\Programs\Python\Python39\lib\site-packages\tweepy\binder.py", line 253, in _call
    return method.execute()
  File "C:\Users\rodri\AppData\Local\Programs\Python\Python39\lib\site-packages\tweepy\binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: Not authorized.
2021-01-27 21:01:10,253 - ERRO - NAO AUTORIZADO
Traceback (most recent call last):
  File "C:\Users\rodri\PythonProjects\PhiloBot-Test-ENV\TWITTER_TEST_ENV\Posting\posting.py", line 79, in posting
    self.tweets_conta = self.obter_tweets(self.api, random_conta)
  File "C:\Users\rodri\PythonProjects\PhiloBot-Test-ENV\TWITTER_TEST_ENV\Posting\posting.py", line 39, in obter_tweets
    resultados = api.user_timeline(screen_name=USERNAME_ACCOUNT,
  File "C:\Users\rodri\AppData\Local\Programs\Python\Python39\lib\site-packages\tweepy\binder.py", line 253, in _call
    return method.execute()
  File "C:\Users\rodri\AppData\Local\Programs\Python\Python39\lib\site-packages\tweepy\binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: Not authorized.
2021-01-27 21:01:10,253 - Not authorized.
Traceback (most recent call last):
  File "C:\Users\rodri\PythonProjects\PhiloBot-Test-ENV\TWITTER_TEST_ENV\Posting\posting.py", line 79, in posting
    self.tweets_conta = self.obter_tweets(self.api, random_conta)
  File "C:\Users\rodri\PythonProjects\PhiloBot-Test-ENV\TWITTER_TEST_ENV\Posting\posting.py", line 39, in obter_tweets
    resultados = api.user_timeline(screen_name=USERNAME_ACCOUNT,
  File "C:\Users\rodri\AppData\Local\Programs\Python\Python39\lib\site-packages\tweepy\binder.py", line 253, in _call
    return method.execute()
  File "C:\Users\rodri\AppData\Local\Programs\Python\Python39\lib\site-packages\tweepy\binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: Not authorized.
