2021-02-02 22:38:25,657 - bad transparency mask
2021-02-02 22:38:35,203 - bad transparency mask
2021-02-02 22:38:45,172 - bad transparency mask
2021-02-02 22:38:54,639 - bad transparency mask
2021-02-02 23:03:48,542 - ERRO NO UNICODE, IGNORANDO...
2021-02-02 23:12:11,488 - Erro: Nome do Filosofo não encontrado. Enviando imagem de erro.
2021-02-02 23:12:11,488 - Philomaker - ERRO AO ENVIAR IMAGEM DE ERRO PARA O USUARIO!
Traceback (most recent call last):
  File "C:\Users\rodri\PythonProjects\PhiloBot-Test-ENV\TWITTER_TEST_ENV\Hashtag\philomaker_engine.py", line 105, in philomaker_engine
    self.user_mentioned_profile_name = f"- {store_name[0]}"
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rodri\PythonProjects\PhiloBot-Test-ENV\TWITTER_TEST_ENV\Hashtag\philomaker_engine.py", line 312, in send_error_no_user_mention
    choice_error_img = random.choice(PHILOMAKER_ERROR_IMAGE_COLLECTION)
  File "C:\Users\rodri\AppData\Local\Programs\Python\Python39\lib\random.py", line 346, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range
2021-02-02 23:12:11,496 - list index out of range
Traceback (most recent call last):
  File "C:\Users\rodri\PythonProjects\PhiloBot-Test-ENV\TWITTER_TEST_ENV\Hashtag\philomaker_engine.py", line 105, in philomaker_engine
    self.user_mentioned_profile_name = f"- {store_name[0]}"
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rodri\PythonProjects\PhiloBot-Test-ENV\TWITTER_TEST_ENV\Hashtag\philomaker_engine.py", line 312, in send_error_no_user_mention
    choice_error_img = random.choice(PHILOMAKER_ERROR_IMAGE_COLLECTION)
  File "C:\Users\rodri\AppData\Local\Programs\Python\Python39\lib\random.py", line 346, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range
2021-02-02 23:20:05,304 - Erro: Nome do Filosofo não encontrado. Enviando imagem de erro.
2021-02-02 23:25:09,630 - IMAGEM NÃO ENCONTRADA
2021-02-02 23:25:09,630 - Enviando imagem de erro...
2021-02-02 23:25:09,630 - [Errno 2] No such file or directory: 'Hashtag/twitter_philo_img.png'
