2021-01-08 22:18:09,071 - 
CONTA ESCOLHIDA
2021-01-08 22:18:09,072 - --------------------------------------------------------
2021-01-08 22:18:09,074 - INICIANDO HASHTAG NA CONTA TESTE
2021-01-08 22:18:11,075 - Escutando tweets da Hashtag: #TestePhilo....
2021-01-08 22:18:11,075 - --------------------------------------------------------

2021-01-08 22:19:44,994 - =============== NOVO TWEET ENCONTRADO ================
2021-01-08 22:19:44,996 - Tweet ID: 1347714626230902786
2021-01-08 22:19:44,996 - Tweet USERNAME: TestePhiloBot
2021-01-08 22:19:44,997 - Adicionado na fila
2021-01-08 22:19:44,997 - --------------------------------------------------------

2021-01-08 22:20:04,999 - ----------------------------------------
2021-01-08 22:20:04,999 - _\|/_ STARTING PHILO_BOT_ENGINE _\|/_ 
2021-01-08 22:20:04,999 - ----------------------------------------
2021-01-08 22:20:04,999 - TAMANHO FILA: 1
2021-01-08 22:20:04,999 - Motor atuando: 1347714626230902786
2021-01-08 22:20:05,364 - STATUS CONVERTIDO: #Testephilo vai pfvr
2021-01-08 22:20:05,365 - STATUS TRATADO: #Testephilo vai pfvr
2021-01-08 22:20:05,425 - Escutando tweets da Hashtag: #TestePhilo....

2021-01-08 22:20:11,642 - Finalizado, enviando: 1347714626230902786
2021-01-08 22:20:11,643 - Itens restantes: 0
2021-01-08 22:20:11,643 - --------------------------------------------------------

2021-01-08 22:20:11,643 - Lista tratada com sucesso.
2021-01-08 22:20:11,643 - _\|/_ TURNING OFF PHILO_BOT_ENGINE _\|/_ 
2021-01-08 22:20:11,651 - Voltando a ouvir tweets...
2021-01-08 22:20:11,651 - Escutando tweets da Hashtag: #TestePhilo....

2021-01-08 22:20:48,537 - =============== NOVO TWEET ENCONTRADO ================
2021-01-08 22:20:48,538 - Tweet ID: 1347714892766343169
2021-01-08 22:20:48,538 - Tweet USERNAME: TestePhiloBot
2021-01-08 22:20:48,538 - Adicionado na fila
2021-01-08 22:20:48,539 - --------------------------------------------------------

2021-01-08 22:21:08,542 - ----------------------------------------
2021-01-08 22:21:08,542 - _\|/_ STARTING PHILO_BOT_ENGINE _\|/_ 
2021-01-08 22:21:08,542 - ----------------------------------------
2021-01-08 22:21:08,543 - TAMANHO FILA: 1
2021-01-08 22:21:08,543 - Motor atuando: 1347714892766343169
2021-01-08 22:21:08,811 - [{'code': 144, 'message': 'No status found with that ID.'}]
2021-01-08 22:21:08,811 - FALHA NA PEGA DO ID - TWEET DELETADO
2021-01-08 22:21:08,811 - Voltando a ouvir tweets...
2021-01-08 22:21:08,811 - Escutando tweets da Hashtag: #TestePhilo....

2021-01-08 22:23:04,760 - 
CONTA ESCOLHIDA
2021-01-08 22:23:04,761 - --------------------------------------------------------
2021-01-08 22:23:04,761 - INICIANDO HASHTAG NA CONTA TESTE
2021-01-08 22:23:06,762 - Escutando tweets da Hashtag: #TestePhilo....
2021-01-08 22:23:06,770 - --------------------------------------------------------

2021-01-08 22:23:21,070 - =============== NOVO TWEET ENCONTRADO ================
2021-01-08 22:23:21,071 - Tweet ID: 1347715532401868807
2021-01-08 22:23:21,071 - Tweet USERNAME: TestePhiloBot
2021-01-08 22:23:21,071 - Adicionado na fila
2021-01-08 22:23:21,072 - --------------------------------------------------------

2021-01-08 22:23:41,073 - ----------------------------------------
2021-01-08 22:23:41,073 - _\|/_ STARTING PHILO_BOT_ENGINE _\|/_ 
2021-01-08 22:23:41,073 - ----------------------------------------
2021-01-08 22:23:41,073 - TAMANHO FILA: 1
2021-01-08 22:23:41,073 - Motor atuando: 1347715532401868807
2021-01-08 22:23:41,338 - [{'code': 144, 'message': 'No status found with that ID.'}]
Traceback (most recent call last):
  File "C:\Users\rodri\PycharmProjects\PhiloBot-TWITTER\PhilosopherBOT-TWITTER-V2.5.3\PhiloBot-Test-ENV\TWITTER_TEST_ENV\Hashtag\hashtag.py", line 162, in philobot_engine
    pegando_status = api.get_status(lastid, tweet_mode='extended', include_entities=False)._json['full_text']
  File "C:\Users\rodri\AppData\Local\Programs\Python\Python38\lib\site-packages\tweepy\binder.py", line 252, in _call
    return method.execute()
  File "C:\Users\rodri\AppData\Local\Programs\Python\Python38\lib\site-packages\tweepy\binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 144, 'message': 'No status found with that ID.'}]
2021-01-08 22:23:41,371 - FALHA NA PEGA DO ID - TWEET DELETADO
Traceback (most recent call last):
  File "C:\Users\rodri\PycharmProjects\PhiloBot-TWITTER\PhilosopherBOT-TWITTER-V2.5.3\PhiloBot-Test-ENV\TWITTER_TEST_ENV\Hashtag\hashtag.py", line 162, in philobot_engine
    pegando_status = api.get_status(lastid, tweet_mode='extended', include_entities=False)._json['full_text']
  File "C:\Users\rodri\AppData\Local\Programs\Python\Python38\lib\site-packages\tweepy\binder.py", line 252, in _call
    return method.execute()
  File "C:\Users\rodri\AppData\Local\Programs\Python\Python38\lib\site-packages\tweepy\binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 144, 'message': 'No status found with that ID.'}]
2021-01-08 22:23:41,371 - Voltando a ouvir tweets...
Traceback (most recent call last):
  File "C:\Users\rodri\PycharmProjects\PhiloBot-TWITTER\PhilosopherBOT-TWITTER-V2.5.3\PhiloBot-Test-ENV\TWITTER_TEST_ENV\Hashtag\hashtag.py", line 162, in philobot_engine
    pegando_status = api.get_status(lastid, tweet_mode='extended', include_entities=False)._json['full_text']
  File "C:\Users\rodri\AppData\Local\Programs\Python\Python38\lib\site-packages\tweepy\binder.py", line 252, in _call
    return method.execute()
  File "C:\Users\rodri\AppData\Local\Programs\Python\Python38\lib\site-packages\tweepy\binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 144, 'message': 'No status found with that ID.'}]
2021-01-08 22:23:41,372 - Escutando tweets da Hashtag: #TestePhilo....
Traceback (most recent call last):
  File "C:\Users\rodri\PycharmProjects\PhiloBot-TWITTER\PhilosopherBOT-TWITTER-V2.5.3\PhiloBot-Test-ENV\TWITTER_TEST_ENV\Hashtag\hashtag.py", line 162, in philobot_engine
    pegando_status = api.get_status(lastid, tweet_mode='extended', include_entities=False)._json['full_text']
  File "C:\Users\rodri\AppData\Local\Programs\Python\Python38\lib\site-packages\tweepy\binder.py", line 252, in _call
    return method.execute()
  File "C:\Users\rodri\AppData\Local\Programs\Python\Python38\lib\site-packages\tweepy\binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 144, 'message': 'No status found with that ID.'}]
2021-01-08 22:25:58,994 - 
CONTA ESCOLHIDA
2021-01-08 22:25:58,998 - --------------------------------------------------------
2021-01-08 22:25:58,998 - INICIANDO HASHTAG NA CONTA TESTE
2021-01-08 22:26:00,998 - Escutando tweets da Hashtag: #TestePhilo....
2021-01-08 22:26:00,998 - --------------------------------------------------------

2021-01-08 22:26:13,970 - =============== NOVO TWEET ENCONTRADO ================
2021-01-08 22:26:13,971 - Tweet ID: 1347716257844523014
2021-01-08 22:26:13,971 - Tweet USERNAME: TestePhiloBot
2021-01-08 22:26:13,972 - Adicionado na fila
2021-01-08 22:26:13,972 - --------------------------------------------------------

2021-01-08 22:26:33,974 - ----------------------------------------
2021-01-08 22:26:33,974 - _\|/_ STARTING PHILO_BOT_ENGINE _\|/_ 
2021-01-08 22:26:33,974 - ----------------------------------------
2021-01-08 22:26:33,974 - TAMANHO FILA: 1
2021-01-08 22:26:33,978 - Motor atuando: 1347716257844523014
2021-01-08 22:26:34,271 - [{'code': 144, 'message': 'No status found with that ID.'}]
Traceback (most recent call last):
  File "C:\Users\rodri\PycharmProjects\PhiloBot-TWITTER\PhilosopherBOT-TWITTER-V2.5.3\PhiloBot-Test-ENV\TWITTER_TEST_ENV\Hashtag\hashtag.py", line 162, in philobot_engine
    pegando_status = api.get_status(lastid, tweet_mode='extended', include_entities=False)._json['full_text']
  File "C:\Users\rodri\AppData\Local\Programs\Python\Python38\lib\site-packages\tweepy\binder.py", line 252, in _call
    return method.execute()
  File "C:\Users\rodri\AppData\Local\Programs\Python\Python38\lib\site-packages\tweepy\binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 144, 'message': 'No status found with that ID.'}]
2021-01-08 22:26:34,273 - FALHA NA PEGA DO ID - TWEET DELETADO
2021-01-08 22:26:34,273 - Voltando a ouvir tweets...
2021-01-08 22:26:34,273 - Escutando tweets da Hashtag: #TestePhilo....

2021-01-08 22:26:44,803 - =============== NOVO TWEET ENCONTRADO ================
2021-01-08 22:26:44,804 - Tweet ID: 1347716387138101252
2021-01-08 22:26:44,805 - Tweet USERNAME: TestePhiloBot
2021-01-08 22:26:44,805 - Adicionado na fila
2021-01-08 22:26:44,806 - --------------------------------------------------------

2021-01-08 22:27:04,808 - ----------------------------------------
2021-01-08 22:27:04,808 - _\|/_ STARTING PHILO_BOT_ENGINE _\|/_ 
2021-01-08 22:27:04,808 - ----------------------------------------
2021-01-08 22:27:04,808 - TAMANHO FILA: 1
2021-01-08 22:27:04,808 - Motor atuando: 1347716387138101252
2021-01-08 22:27:05,138 - STATUS CONVERTIDO: #Testephilo aaaaaaa
2021-01-08 22:27:05,138 - STATUS TRATADO: #Testephilo aaaaaaa
2021-01-08 22:27:05,196 - Escutando tweets da Hashtag: #TestePhilo....

2021-01-08 22:27:11,586 - Finalizado, enviando: 1347716387138101252
2021-01-08 22:27:11,586 - Itens restantes: 0
2021-01-08 22:27:11,587 - --------------------------------------------------------

2021-01-08 22:27:11,587 - Lista tratada com sucesso.
2021-01-08 22:27:11,587 - _\|/_ TURNING OFF PHILO_BOT_ENGINE _\|/_ 
2021-01-08 22:27:11,587 - Voltando a ouvir tweets...
2021-01-08 22:27:11,587 - Escutando tweets da Hashtag: #TestePhilo....

